"""empty message

Revision ID: 79648d7cf8ef
Revises: 2ba2e24a7b8e
Create Date: 2025-04-16 20:31:26.400281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79648d7cf8ef'
down_revision = '2ba2e24a7b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
